name: Integration

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 12

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    
  build:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 12.x
        - 13.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true
        
  release: 
    needs: build
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: 
        - 12
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      - uses: phish108/github-tag-action@p1.17.4
        id: tagger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
      - run: echo ${{ steps.tagger.outputs.tag }} ${{ steps.tagger.outputs.new_tag }}
      - run: npm --no-git-tag-version version ${{ steps.tagger.outputs.new_tag }}
