name: Integration

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 12

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    
  build:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 12.x
        - 13.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true
        
  release: 
    needs: build
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: 
        - 12
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm ci
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - uses: phish108/github-tag-action@p1.17.4
        id: tagger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
      - run: |
          whoami
          echo ${{ steps.tagger.outputs.tag }} ${{ steps.tagger.outputs.new_tag }}
      - run: npm --no-git-tag-version --allow-same-version version ${{ steps.tagger.outputs.new_tag }}
      - run: git commit -m "version bump to $NPM_VERSION" -a
        env: 
          NPM_VERSION: ${{ steps.tagger.outputs.new_tag }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: phish108/github-tag-action@p1.17.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
  
  publish-npm:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://npm.pkg.github.com/
          scope: '@phish108'
          always-auth: 'false'
      - run: npm ci
      - run: | 
          echo ${RUNNER_TEMP}
          cat ${RUNNER_TEMP}/.npmrc
          npm config list
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
