name: Integration

on: [push]

jobs:
  # lint:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: 
  #       - 12

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - run: npm run lint
    
  build:
    # needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 12.x

    steps:
    - run: echo 00008
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: "true"
    - uses: phish108/jstest-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN}}
        dry-run: "false"
        branch: "foobar"

  # merge: 
  #   needs: build
  #   if: github.actor == 'phish108' ||  startsWith(github.actor, 'dependabot')
    
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: automerge
  #     uses: "pascalgn/automerge-action@5ad9f38505afff96c6ad2d1c1bf2775135a7d309"
  #     env:
  #       GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  #       MERGE_LABELS: ""

  # release: 
  #   needs: merge
  #   if: github.actor == 'phish108' || startsWith(github.actor, 'dependabot')

  #   runs-on: ubuntu-latest

  #   steps:
  #     - id: contributor 
  #       run: echo ::set-output name=release::minor
  #       if: github.actor == 'phish108'

  #     - id: bot
  #       run: echo ::set-output name=release::patch
  #       if: startsWith(github.actor, 'dependabot')

  #     - uses: actions/checkout@v2
  #       with:
  #         ref: master

  #     - run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  
  #     - uses: phish108/github-tag-action@master
  #       id: tagger
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITHUB_REF: "refs/heads/master"
  #         DEFAULT_BUMP: ${{ steps.contributor.outputs.release || steps.bot.outputs.release }}
  #         DRY_RUN: true

  #     - run: npm --no-git-tag-version --allow-same-version version ${{ steps.tagger.outputs.new_tag }}

  #     - run: git commit -m "version bump to $NPM_VERSION" -a
  #       env: 
  #         NPM_VERSION: ${{ steps.tagger.outputs.new_tag }}

  #     - name: Push changes
  #       uses: ad-m/github-push-action@master
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}

  #     - uses: phish108/github-tag-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GITHUB_REF: "refs/heads/master"
  #         DEFAULT_BUMP: ${{ steps.contributor.outputs.release || steps.bot.outputs.release }}
  #         WITH_V: true

  # publish-npm:
  #   needs: release
  #   if: github.actor == 'phish108' ||  startsWith(github.actor, 'dependabot')

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         ref: master
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm ci
  #     - run: npm publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  
  