name: Integration

on: 
  push:
    branches:
      - master

jobs:
  # lint:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: 
  #       - 12

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - run: npm ci
  #   - run: npm run lint
    
  build:
    # needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
        - 20.x

    steps:
    - run: echo 00010
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: "true"

